export const IdeationRules = [
  {
    id: 1,
    status: true,
    text: 'Submission Item: Concept Paper: Provide a written summary of what your solution is, how it works and what is required for it to work successful. Address each of the below questions in your submission. -Question 1 -Question...',
    readOnly: true,
  },
  {
    id: 2,
    status: true,
    text: 'Submission Item: Demo Video: Provide a video (Max 5 minutes) that demonstrates your solution or your solution concept. Your video should cover the following points -Point A -Point...',
    readOnly: true,
  },
  {
    id: 3,
    status: true,
    text: 'List basic information about your submission including -Project Name -Team Members -Solution title or tagline -Project Keywords -Team location and zipcode if a US only eligible challenge.',
    readOnly: true,
  },
  {
    id: 4,
    status: false,
    text: 'Submission Item: Solution Summary: Provide a summary of no more than 300 words that describes your solution.',
    readOnly: true,
  },
  {
    id: 5,
    status: false,
    text: 'Challenge Sponsor: The official sponsor of this challenge is <insert your company name>. The Challenge is hosted on behalf of Challenge Sponsor by Floor23 Digital, LLC. ("Floor23"). Floor23 is an independent contractor of Challenge Sponsor, and is not a party to this or any agreement between you and Challenge Sponsor. Floor23 will perform certain administrative functions relating to hosting the Challenge, and you agree to abide by the provisions relating to Floor23 under these Rules. As a Floor23 InnoBear account holder and user of the Floor23 Challenge platform, remember you have accepted and are subject to the Floor23 Terms of Service at www.Floor23digital.com/terms in addition to these Rules.',
    readOnly: true,
  },
  {
    id: 6,
    status: false,
    text: 'Geographic Eligibility: Individual competitors and teams may originate from either the U.S. or a designated country (see definition of designated country at https://www.acquisition.gov/far/part-25#FAR_25_003), OR have been substantially transformed in the US or designated country prior to solution delivery pursuant to FAR 25.403(c). And any country where the United States federal sanctions do not prohibit participation (see: https://www.treasury.gov/resourcecenter/sanctions/Programs/Pages/Programs.aspx)',
    readOnly: true,
  },
  {
    id: 7,
    status: false,
    text: 'Age Eligibility: To be eligible to enter the challenge you must be the older of 18 years old or the age of majority in your jurisdiction of residence (unless otherwise agreed to by           Challenge Sponsor and appropriate parental/guardian consents have been obtained by Challenge Sponsor).',
    readOnly: true,
  },
  {
    id: 8,
    status: false,
    text: 'Restricted Participation: Unless otherwise stated in the Specific Challenge Rules above or prohibited by internal policies of the Challenge Entities, employees, interns, contractors,            officers and directors of Challenge Entities may enter and participate in the Challenge, but are not eligible to win any Prizes. "Challenge Entities" means the Challenge Sponsor, Floor23 Inc., and their respective parent companies, subsidiaries and affiliates. If you are such a participant from a Challenge Entity, you are subject to all applicable internal policies of your employer with respect to your participation.',
    readOnly: true,
  },
  {
    id: 9,
    status: false,
    text: 'Submissions must be made in <English>. All challenge related communication will be in <English>',
    readOnly: true,
  },
  {
    id: 10,
    status: false,
    text: 'General Eligibility: To be eligible to enter the Challenge, you must (i) be a registered account holder at Innobear.Floor23digital. com…location of the Challenge Website. (ii) comply with all the terms of the challenge as defined in the Challenge Rules.',
    readOnly: true,
  },
  {
    id: 11,
    status: false,
    text: 'Individual/Team Entries: The challenge is open to participation as an individual or as a team',
    readOnly: true,
  },
  {
    id: 12,
    status: false,
    text: 'Eligibility Verification: The Official Sponsor reserves the right to verify eligibility and to adjudicate on any dispute at any time. If you provide any false information relating to the Challenge concerning your identity, residency, mailing address, telephone number, email address, ownership of right, or information required for entering the Challenge, you may be immediately disqualified from the Challenge',
    readOnly: true,
  },
  {
    id: 13,
    status: false,
    text: 'Intellectual Property: Intellectual Property: Awarded/Incentivized participants agree to an irrevocable, paid-up, royalty-free non exclusive worldwide license to reproduce, publish, post, link to, share, and display publicly (e.g., on websites) the submission and abstracts on the web or elsewhere will be provided to the Challenge Sponsor. Participants agree not to make any Submission that: (i) infringes any third party proprietary rights, intellectual property rights, industrial property rights, personal or moral rights or any other rights, including without limitation, copyright, trademark, patent, trade secret, privacy, publicity or confidentiality obligations, or defames any person; or (ii) otherwise violates any',
    readOnly: true,
  },
  {
    id: 14,
    status: false,
    text: ' Pre-Requisite Expertise: Specific qualifications or expertise in the fields of <insert fields relevant to the Challenge i.e. biology, aerospace, healthcare, etc> <are> OR <are not> required. Outside individuals and non-expert team <are> OR <are not> encouraged to compete and propose new solutions.',
    readOnly: true,
  },
  {
    id: 15,
    status: false,
    text: 'Selecting Winners: Each Submission will be scored and ranked by the evaluation metrics stated on the Challenge Website',
    readOnly: true,
  },
  {
    id: 16,
    status: false,
    text: 'Challenge Period: The “Challenge Period” will run from the Start Date and time to the Final Submission Deadline as listed on the Challenge Website. Within the Challenge period, the            Challenge Sponsor reserves the right to update or introduce additional deadlines during the Challenge Period. Any updated or additional deadlines will be publicized on the Challenge            Website. It is your responsibility to check the Challenge Website regularly to stay informed of any deadline changes. YOU ARE RESPONSIBLE FOR DETERMINING THE',
    readOnly: true,
  },
];

export const EngagementRules = [
  {
    id: 1,
    status: true,
    text: 'Submission Item: Concept Paper: Provide a written summary of what your solution is, how it works and what is required for it to work successful. Address each of the below questions in            your submission. -Question 1 -Question...',
    readOnly: true,
  },
  {
    id: 2,
    status: true,
    text: 'Submission Item: Cover Page: List basic information about your submission including; -Project Name -Team Members           -Solution title or tagline -Project Keywords -Team location and zipcode if a US only eligible challenge.',
    readOnly: false,
  },
  {
    id: 3,
    status: true,
    text: ' Submission Item: Solution Summary: Provide a summary of no more than 300 words that describes your solution.',
    readOnly: false,
  },
  {
    id: 4,
    status: false,
    text: 'Submission Item: Letters of Support: Attach one-page letters of support, intent, or commitment from relevant entities (e.g., potential users of the proposed innovation or strategic            manufacturing partners) to provide context. Letters of support from partners or others that are critical to the success of your proposed solution will likely increase your score. General letters of support from parties that are not critical to the execution of your solution will likely not factor into your score. Please do not submit multi-page letters.',
    readOnly: true,
  },
  {
    id: 4,
    status: false,
    text: 'Challenge Sponsor: The official sponsor of this challenge is <insert your company name>. The Challenge is hosted on behalf of Challenge Sponsor by Floor23 Digital, LLC. ("Floor23"). Floor23 is an independent contractor of Challenge Sponsor, and is not a party to this or any agreement between you and Challenge Sponsor. Floor23 will perform certain administrative functions relating to hosting the Challenge, and you agree to abide by the provisions relating to Floor23 under these Rules. As a Floor23 InnoBear account holder and user of the Floor23 Challenge platform, remember you have accepted and are subject to the Floor23 Terms of Service at www.Floor23digital.com/terms in addition to these Rules.',
    readOnly: true,
  },
  {
    id: 5,
    status: false,
    text: 'Geographic Eligibility: Individual competitors and teams may originate from either the U.S. or a designated country (see definition of designated country at https://www.acquisition.gov/far/part-25#FAR_25_003), OR have been substantially  transformed in the US or designated country prior to solution delivery pursuant to FAR 25.403(c). And any country where the United States federal sanctions do not prohibit   participation (see: https://www.treasury.gov/resourcecenter/sanctions/Programs/Pages/Programs.aspx)',
    readOnly: true,
  },
  {
    id: 6,
    status: false,
    text: 'Age Eligibility: To be eligible to enter the challenge you must be the older of 18 years old or the age of majority in your jurisdiction of residence (unless otherwise agreed to by Challenge Sponsor and appropriate parental/guardian consents have been obtained by Challenge Sponsor).',
    readOnly: true,
  },
  {
    id: 7,
    status: false,
    text: 'Restricted Participation: Unless otherwise stated in the Specific Challenge Rules above or prohibited by internal policies of the Challenge Entities, employees, interns, contractors, officers and directors of Challenge Entities may enter and participate in the Challenge, but are not eligible to win any Prizes. "Challenge Entities" means the Challenge Sponsor, Floor23 Inc., and            their respective parent companies, subsidiaries and affiliates. If you are such a participant from a Challenge Entity, you are subject to all applicable internal policies of your employer with respect to your participation.',
    readOnly: true,
  },
  {
    id: 8,
    status: false,
    text: 'Submission Language: Submissions must be made in <English>. All challenge related communication will be in <English>.',
    readOnly: true,
  },
  {
    id: 9,
    status: false,
    text: 'General Eligibility: To be eligible to enter the Challenge, you must (i) be a registered account holder at Innobear.Floor23digital. com…location of the Challenge Website. (ii) comply with all the terms of the challenge as defined in the Challenge Rules.',
    readOnly: true,
  },
  {
    id: 10,
    status: false,
    text: 'Individual/Team Entries: The challenge is open to participation as an individual or as a team',
    readOnly: true,
  },
  {
    id: 11,
    status: false,
    text: 'Eligibility Verification: The Official Sponsor reserves the right to verify eligibility and to adjudicate on any dispute at any time. If you provide any false information relating to the Challenge concerning your identity, residency, mailing address, telephone number, email address, ownership of right, or information required for entering the Challenge, you may be immediately disqualified from the Challenge',
    readOnly: true,
  },
  {
    id: 12,
    status: false,
    text: 'Intellectual Property: Intellectual Property: Awarded/Incentivized participants agree to an irrevocable, paid-up, royalty-free non exclusive worldwide license to reproduce, publish, post, link to, share, and display publicly (e.g., on websites) the submission and abstracts on the web or elsewhere will be provided to the Challenge Sponsor. Participants agree not to make any            Submission that: (i) infringes any third party proprietary rights, intellectual property rights, industrial property rights, personal or moral rights or any other rights, including without            limitation, copyright, trademark, patent, trade secret, privacy, publicity or confidentiality obligations, or defames any person; or (ii) otherwise violates any',
    readOnly: true,
  },
  {
    id: 13,
    status: false,
    text: 'Pre-Requisite Expertise: Specific qualifications or expertise in the fields of <insert fields relevant to the Challenge i.e. biology, aerospace, healthcare, etc> <are> OR <are not> required. Outside individuals and non-expert team <are> OR <are not> encouraged to compete and propose new solutions.',
    readOnly: true,
  },
  {
    id: 14,
    status: false,
    text: 'Selecting Winners: Each Submission will be scored and ranked by the evaluation metrics stated on the Challenge Website',
    readOnly: true,
  },
  {
    id: 15,
    status: false,
    text: 'Challenge Period: The “Challenge Period” will run from the Start Date and time to the Final Submission Deadline as listed on the Challenge Website. Within the Challenge period, the            Challenge Sponsor reserves the right to update or introduce additional deadlines during the Challenge Period. Any updated or additional deadlines will be publicized on the Challenge            Website. It is your responsibility to check the Challenge Website regularly to stay informed of any deadline changes. YOU ARE RESPONSIBLE FOR DETERMINING THE',
    readOnly: true,
  },
];

export const AnalysisRules = [
  {
    id: 1,
    status: true,
    text: 'Submission Item: Demo Video: Provide a video (Max 5 minutes) that demonstrates your solution or your solution concept. Your video should cover the following points -Point A -Point...',
    readOnly: true,
  },
  {
    id: 2,
    status: true,
    text: 'Submission Item: Cover Page: List basic information about your submission including; o -Project Name o -Team Members o -Solution title or tagline o -Project Keywords o -Team location and zipcode if a US only eligible challenge.',
    readOnly: false,
  },
  {
    id: 3,
    status: true,
    text: 'Submission Item: Solution Summary: Provide a summary of no more than 300 words that describes your solution.',
    readOnly: false,
  },
  {
    id: 4,
    status: false,
    text: 'Challenge Sponsor: The official sponsor of this challenge is <insert your company name>. The Challenge is hosted on behalf of Challenge Sponsor by Floor23 Digital, LLC. ("Floor23"). Floor23 is an independent contractor of Challenge Sponsor, and is not a party to this or any agreement between you and Challenge Sponsor. Floor23 will perform certain administrative functions relating to hosting the Challenge, and you agree to abide by the provisions relating to Floor23 under these Rules. As a Floor23 InnoBear account holder and user of the Floor23 Challenge platform, remember you have accepted and are subject to the Floor23 Terms of Service at www.Floor23digital.com/terms in addition to these Rules.',
    readOnly: true,
  },
  {
    id: 5,
    status: false,
    text: 'Geographic Eligibility: Individual competitors and teams may originate from either the U.S. or a designated country (see definition of designated country at https://www.acquisition.gov/far/part-25#FAR_25_003), OR have been substantially            transformed in the US or designated country prior to solution delivery pursuant to FAR 25.403(c). And any country where the United States federal sanctions do not prohibit participation (see: https://www.treasury.gov/resourcecenter/sanctions/Programs/Pages/Programs.aspx)',
    readOnly: true,
  },
  {
    id: 6,
    status: false,
    text: 'Age Eligibility: To be eligible to enter the challenge you must be the older of 18 years old or the age of majority in your jurisdiction of residence (unless otherwise agreed to by Challenge Sponsor and appropriate parental/guardian consents have been obtained by Challenge Sponsor).',
    readOnly: false,
  },
  {
    id: 7,
    status: false,
    text: 'Restricted Participation: Unless otherwise stated in the Specific Challenge Rules above or prohibited by internal policies of the Challenge Entities, employees, interns, contractors, officers and directors of Challenge Entities may enter and participate in the Challenge, but are not eligible to win any Prizes. "Challenge Entities" means the Challenge Sponsor, Floor23 Inc., and            their respective parent companies, subsidiaries and affiliates. If you are such a participant from a Challenge Entity, you are subject to all applicable internal policies of your employer with            respect to your participation.',
    readOnly: false,
  },
  {
    id: 8,
    status: false,
    text: 'General Eligibility: To be eligible to enter the Challenge, you must (i) be a registered account holder at Innobear.Floor23digital. com…location of the Challenge Website. (ii) comply with all the terms of the challenge as defined in the Challenge Rules.',
    readOnly: false,
  },
  {
    id: 9,
    status: false,
    text: 'Individual/Team Entries: The challenge is open to participation as an individual or as a team',
    readOnly: false,
  },
  {
    id: 10,
    status: false,
    text: 'Eligibility Verification: The Official Sponsor reserves the right to verify eligibility and to adjudicate on any dispute at any time. If you provide any false information relating to the Challenge concerning your identity, residency, mailing address, telephone number, email address, ownership of right, or information required for entering the Challenge, you may be immediately disqualified from the Challenge',
    readOnly: false,
  },
  {
    id: 11,
    status: false,
    text: 'Intellectual Property: Intellectual Property: Awarded/Incentivized participants agree to an irrevocable, paid-up, royalty-free non exclusive worldwide license to reproduce, publish, post, link to, share, and display publicly (e.g., on websites) the submission and abstracts on the web or elsewhere will be provided to the Challenge Sponsor. Participants agree not to make any Submission that: (i) infringes any third party proprietary rights, intellectual property rights, industrial property rights, personal or moral rights or any other rights, including without limitation, copyright, trademark, patent, trade secret, privacy, publicity or confidentiality obligations, or defames any person; or (ii) otherwise violates any',
    readOnly: false,
  },
  {
    id: 12,
    status: false,
    text: 'Pre-Requisite Expertise: Specific qualifications or expertise in the fields of <insert fields relevant to the Challenge i.e. biology, aerospace, healthcare, etc> <are> OR <are not> required. Outside   individuals and non-expert team <are> OR <are not> encouraged to compete and propose new solutions.',
    readOnly: false,
  },
  {
    id: 13,
    status: false,
    text: 'Challenge Period: The “Challenge Period” will run from the Start Date and time to the Final Submission Deadline as listed on the Challenge Website. Within the Challenge period, the Challenge Sponsor reserves the right to update or introduce additional deadlines during the Challenge Period. Any updated or additional deadlines will be publicized on the Challenge Website. It is your responsibility to check the Challenge Website regularly to stay informed of any deadline changes. YOU ARE RESPONSIBLE FOR DETERMINING THE',
    readOnly: false,
  },
];

export const BuildRules = [
  {
    id: 1,
    status: true,
    text: 'Submission Item: Concept Paper: Provide a written summary of what your solution is, how it works and what is required for it to work successful. Address each of the below questions in your submission. -Question 1   -Question...',
    readOnly: true,
  },
  {
    id: 2,
    status: true,
    text: 'Submission Item: Prototype: Provide a < physical> OR< digital> prototype of your solution with the following specifications in mind. -Specification 1 -Specification...',
    readOnly: false,
  },
  {
    id: 3,
    status: true,
    text: 'Submission Item: Demo Video: Provide a video (Max 5 minutes) that demonstrates your solution or your solution concept. Your video should cover the following points -Point A -Point...',
    readOnly: false,
  },
  {
    id: 4,
    status: false,
    text: 'Submission Item: Cover Page: List basic information about your submission including; o -Project Name o -Team Members o -Solution title or tagline o -Project Keywords o -Team location and zipcode if a US only eligible challenge.',
    readOnly: true,
  },
  {
    id: 5,
    status: false,
    text: 'Submission Item: Solution Summary: Provide a summary of no more than 300 words that describes your solution.',
    readOnly: true,
  },
  {
    id: 6,
    status: false,
    text: 'Submission Item: Letters of Support: Attach one-page letters of support, intent, or commitment from relevant entities (e.g., potential users of the proposed innovation or strategic falsemanufacturing partners) to provide context. Letters of support from partners or others that are critical to the success of your proposed solution will likely increase your score. General letters of support from parties that are not critical to the execution of your solution will likely not factor into your score. Please do not submit multi-page letters.',
    readOnly: true,
  },
  {
    id: 7,
    status: false,
    text: 'Submission Item: Readiness Proof: Provide the following artifacts to demonstrate your solution’s readiness to advance to the next <stage of the Challenge> OR <innovation stage> Proof Point Item #1 Proof Point Item ...',
    readOnly: true,
  },
  {
    id: 8,
    status: false,
    text: 'Challenge Sponsor: The official sponsor of this challenge is <insert your company name>. The Challenge is hosted on behalf of Challenge Sponsor by Floor23 Digital, LLC. ("Floor23"). Floor23 is an independent contractor of Challenge Sponsor, and is not a party to this or any agreement between you and Challenge Sponsor. Floor23 will perform certain administrative functions relating to hosting the Challenge, and you agree to abide by the provisions relating to Floor23 under these Rules. As a Floor23 InnoBear account holder and user of the Floor23 Challenge platform, remember you have accepted and are subject to the Floor23 Terms of Service at www.Floor23digital.com/terms in addition to these Rules.',
    readOnly: true,
  },
  {
    id: 9,
    status: false,
    text: 'Geographic Eligibility: Individual competitors and teams may originate from either the U.S. or a designated country (see definition of designated country at https://www.acquisition.gov/far/part-25#FAR_25_003), OR have been substantially falsetransformed in the US or designated country prior to solution delivery pursuant to FAR 25.403(c). And any country where the United States federal sanctions do not prohibit participation (see: https://www.treasury.gov/resourcecenter/sanctions/Programs/Pages/Programs.aspx)',
    readOnly: true,
  },
  {
    id: 10,
    status: false,
    text: 'Age Eligibility: To be eligible to enter the challenge you must be the older of 18 years old or the age of majority in your jurisdiction of residence (unless otherwise agreed to by Challenge Sponsor and appropriate parental/guardian consents have been obtained by Challenge Sponsor).',
    readOnly: true,
  },
  {
    id: 11,
    status: false,
    text: 'Insurance Requirements: Due to the nature of this challenge it is <required> OR <recommended but not required> that the participants carry <types of insurance> in a minimum amount of <enter dollar value and relevant detail> in orderto protect <insert what this policy will protect against>.',
    readOnly: true,
  },

  {
    id: 12,
    status: false,
    text: 'Restricted Participation: Unless otherwise stated in the Specific Challenge Rules above or prohibited by internal policies of the Challenge Entities, employees, interns, contractors, officers and directors of Challenge Entities may enter and participate in the Challenge, but are not eligible to win any Prizes. "Challenge Entities" means the Challenge Sponsor, Floor23 Inc., and their respective parent companies, subsidiaries and affiliates. If you are such a participant from a Challenge Entity, you are subject to all applicable internal policies of your employer with falserespect to your participation.',
    readOnly: true,
  },
  {
    id: 13,
    status: false,
    text: 'Insurance Requirements: Due to the nature of this challenge it is <required> OR <recommended but not required> that the participants carry <types of insurance> in a minimum amount of <enter dollar value and relevant detail> in orderto protect <insert what this policy will protect against>.',
    readOnly: true,
  },
  {
    id: 14,
    status: false,
    text: 'Submission Language: Submissions must be made in <English>. All challenge related communication will be in <English>.',
    readOnly: true,
  },
  {
    id: 15,
    status: false,
    text: 'General Eligibility: To be eligible to enter the Challenge, you must (i) be a registered account holder at Innobear.Floor23digital. com…location of the Challenge Website. (ii) comply with all the terms of the challenge as defined in the Challenge Rules.',
    readOnly: true,
  },
  {
    id: 16,
    status: false,
    text: 'Individual/Team Entries: The challenge is open to participation as an individual or as a team',
    readOnly: true,
  },
  {
    id: 17,
    status: false,
    text: 'Eligibility Verification: The Official Sponsor reserves the right to verify eligibility and to adjudicate on any dispute at any time. If you provide any false information relating to the Challenge concerning your identity, residency, mailing address, telephone number, email address, ownership of right, or information required for entering the Challenge, you may be immediately disqualified from the Challenge',
    readOnly: true,
  },
  {
    id: 18,
    status: false,
    text: 'Intellectual Property: Intellectual Property: Awarded/Incentivized participants agree to an irrevocable, paid-up, royalty-free non exclusive worldwide license to reproduce, publish, post, link to, share, and display publicly (e.g., on websites) the submission and abstracts on the web or elsewhere will be provided to the Challenge Sponsor. Participants agree not to make any falseSubmission that: (i) infringes any third party proprietary rights, intellectual property rights, industrial property rights, personal or moral rights or any other rights, including without             limitation, copyright, trademark, patent, trade secret, privacy, publicity or confidentiality obligations, or defames any person; or (ii) otherwise violates any',
    readOnly: true,
  },
  {
    id: 19,
    status: false,
    text: 'Pre-Requisite Expertise: Specific qualifications or expertise in the fields of <insert fields relevant to the Challenge i.e. biology, aerospace, healthcare, etc> <are> OR <are not> required. Outside   individuals and non-expert team <are> OR <are not> encouraged to compete and propose new solutions.',
    readOnly: true,
  },
  {
    id: 20,
    status: false,
    text: 'Challenge Period: The “Challenge Period” will run from the Start Date and time to the Final Submission Deadline as listed on the Challenge Website. Within the Challenge period, the Challenge Sponsor reserves the right to update or introduce additional deadlines during the Challenge Period. Any updated or additional deadlines will be publicized on the Challenge Website. It is your responsibility to check the Challenge Website regularly to stay informed of any deadline changes. YOU ARE RESPONSIBLE FOR DETERMINING THE',
    readOnly: true,
  },
];

export const Acceleration = [
  {
    id: 1,
    status: true,
    text: 'Submission Item: Concept Paper: Provide a written summary of what your solution is, how it works and what is required for it to work successful. Address each of the below questions in            your submission. -Question 1 -Question...',
    readOnly: true,
  },
  {
    id: 2,
    status: true,
    text: 'Submission Item: Prototype: Provide a <physical> OR< digital> prototype of your solution with the following specifications in mind. -Specification 1 -Specification...',
    readOnly: false,
  },
  {
    id: 3,
    status: true,
    text: 'Submission Item: Demo Video: Provide a video (Max 5 minutes) that demonstrates your solution or your solution concept. Your video should cover the following points -Point A -Point...',
    readOnly: false,
  },
  {
    id: 4,
    status: false,
    text: 'Submission Item: Cover Page: List basic information about your submission including; o -Project Name o -Team Members o -Solution title or tagline o -Project Keywords o -Team location and zipcode if a US only eligible challenge.',
    readOnly: true,
  },
  {
    id: 5,
    status: false,
    text: 'Submission Item: Solution Summary: Provide a summary of no more than 300 words that describes your solution.',
    readOnly: true,
  },
  {
    id: 6,
    status: false,
    text: 'Submission Item: Letters of Support: Attach one-page letters of support, intent, or commitment from relevant entities (e.g., potential users of the proposed innovation or strategic falsemanufacturing partners) to provide context. Letters of support from partners or others that are critical to the success of your proposed solution will likely increase your score. General letters of support from parties that are not critical to the execution of your solution will likely not factor into your score. Please do not submit multi-page letters.',
    readOnly: true,
  },
  {
    id: 7,
    status: false,
    text: 'Submission Item: Readiness Proof: Provide the following artifacts to demonstrate your solution’s readiness to advance to the next <stage of the Challenge> OR <innovation stage> Proof Point Item #1 Proof Point Item ...',
    readOnly: true,
  },

  {
    id: 8,
    status: false,
    text: 'Challenge Sponsor: The official sponsor of this challenge is <insert your company name>. The Challenge is hosted on behalf of Challenge Sponsor by Floor23 Digital, LLC. ("Floor23"). Floor23 is an independent contractor of Challenge Sponsor, and is not a party to this or any agreement between you and Challenge Sponsor. Floor23 will perform certain administrative functions relating to hosting the Challenge, and you agree to abide by the provisions relating to Floor23 under these Rules. As a Floor23 InnoBear account holder and user of the Floor23 Challenge platform, remember you have accepted and are subject to the Floor23 Terms of Service at www.Floor23digital.com/terms in addition to these Rules.',
    readOnly: true,
  },
  {
    id: 9,
    status: false,
    text: 'Geographic Eligibility: Individual competitors and teams may originate from either the U.S. or a designated country (see definition of designated country at https://www.acquisition.gov/far/part-25#FAR_25_003), OR have been substantially falsetransformed in the US or designated country prior to solution delivery pursuant to FAR 25.403(c). And any country where the United States federal sanctions do not prohibit participation (see: https://www.treasury.gov/resourcecenter/sanctions/Programs/Pages/Programs.aspx)',
    readOnly: true,
  },
  {
    id: 10,
    status: false,
    text: 'Age Eligibility: To be eligible to enter the challenge you must be the older of 18 years old or the age of majority in your jurisdiction of residence (unless otherwise agreed to by Challenge Sponsor and appropriate parental/guardian consents have been obtained by Challenge Sponsor).',
    readOnly: true,
  },
  {
    id: 11,
    status: false,
    text: 'Restricted Participation: Unless otherwise stated in the Specific Challenge Rules above or prohibited by internal policies of the Challenge Entities, employees, interns, contractors, officers and directors of Challenge Entities may enter and participate in the Challenge, but are not eligible to win any Prizes. "Challenge Entities" means the Challenge Sponsor, Floor23 Inc., and falsetheir respective parent companies, subsidiaries and affiliates. If you are such a participant from a Challenge Entity, you are subject to all applicable internal policies of your employer with            respect to your participation.',
    readOnly: true,
  },
  {
    id: 12,
    status: false,
    text: 'Submission Language: Submissions must be made in <English>. All challenge related communication will be in <English>.',
    readOnly: true,
  },
  {
    id: 13,
    status: false,
    text: 'General Eligibility: To be eligible to enter the Challenge, you must (i) be a registered account holder at Innobear.Floor23digital. com…location of the Challenge Website. (ii) comply with all the terms of the challenge as defined in the Challenge Rules.',
    readOnly: true,
  },
  {
    id: 14,
    status: false,
    text: 'Individual/Team Entries: The challenge is open to participation as an individual or as a team',
    readOnly: true,
  },
  {
    id: 15,
    status: false,
    text: 'Eligibility Verification: The Official Sponsor reserves the right to verify eligibility and to adjudicate on any dispute at any time. If you provide any false information relating to the Challenge concerning your identity, residency, mailing address, telephone number, email address, ownership of right, or information required for entering the Challenge, you may be immediately disqualified from the Challenge',
    readOnly: true,
  },
  {
    id: 16,
    status: false,
    text: 'Intellectual Property: Intellectual Property: Awarded/Incentivized participants agree to an irrevocable, paid-up, royalty-free non exclusive worldwide license to reproduce, publish, post, link to, share, and display publicly (e.g., on websites) the submission and abstracts on the web or elsewhere will be provided to the Challenge Sponsor. Participants agree not to make any falseSubmission that: (i) infringes any third party proprietary rights, intellectual property rights, industrial property rights, personal or moral rights or any other rights, including without             limitation, copyright, trademark, patent, trade secret, privacy, publicity or confidentiality obligations, or defames any person; or (ii) otherwise violates any',
    readOnly: true,
  },
  {
    id: 17,
    status: false,
    text: 'Pre-Requisite Expertise: Specific qualifications or expertise in the fields of <insert fields relevant to the Challenge i.e. biology, aerospace, healthcare, etc> <are> OR <are not> required. Outside   individuals and non-expert team <are> OR <are not> encouraged to compete and propose new solutions.',
    readOnly: true,
  },
  {
    id: 18,
    status: false,
    text: 'Selecting Winners: Each Submission will be scored and ranked by the evaluation metrics stated on the Challenge Website',
    readOnly: true,
  },
  {
    id: 19,
    status: false,
    text: 'Challenge Period: The “Challenge Period” will run from the Start Date and time to the Final Submission Deadline as listed on the Challenge Website. Within the Challenge period, the            Challenge Sponsor reserves the right to update or introduce additional deadlines during the Challenge Period. Any updated or additional deadlines will be publicized on the Challenge            Website. It is your responsibility to check the Challenge Website regularly to stay informed of any deadline changes. YOU ARE RESPONSIBLE FOR DETERMINING THE',
    readOnly: true,
  },
];
